added basic key members
anirudhprabhakaran3/pedes-website pull request #11
Opened 2023-10-04 12:49 UTC by MeerIsmailAli

please review and let me know what to adjust and change accordingly

2023-10-05 06:44 UTC, anirudhprabhakaran3 requested changes

2023-10-05 06:44 UTC, anirudhprabhakaran3 commented on web/templates/pages/committee.html
- Don't have tables stretching full page
- Why are tables in dark mode. Light mode tables are enough.

2023-10-05 19:50 UTC, MeerIsmailAli commented on web/templates/pages/committee.html
I have made the changes requested in the new commit ,review needed

2023-10-06 06:00 UTC, anirudhprabhakaran3 approved these changes

2023-10-06 06:00 UTC, merged