timeline and tracks updated
anirudhprabhakaran3/pedes-website pull request #12
Opened 2023-10-04 15:36 UTC by ameen-11

Let me know if this works , or else let me know the changes.

2023-10-05 06:39 UTC, anirudhprabhakaran3 requested changes

2023-10-05 06:39 UTC, anirudhprabhakaran3 commented on web/pages/urls.py
> +urlpatterns = [path("", home, name="home"),path("important_dates/",important_dates, name="important_dates"),path("tracks/",tracks, name="tracks")]
Please run a formatter / linter on your code.

2023-10-05 06:39 UTC, anirudhprabhakaran3 commented on web/pedes/urls.py
> +urlpatterns = [path("admin/", admin.site.urls), path("", include("pages.urls")) ]
Same here, run a formatter or a linter.

2023-10-05 06:39 UTC, anirudhprabhakaran3 commented on web/templates/pages/tracks.html
Do not just copy paste from home page 😃 
Fix the color scheme and make the page look good. Since the page has only one section, no need to have that as a dark mode sort of color scheme.

2023-10-06 15:50 UTC, ameen-11 commented on web/pages/urls.py
> +urlpatterns = [path("", home, name="home"),path("important_dates/",important_dates, name="important_dates"),path("tracks/",tracks, name="tracks")]
ran a formatter

2023-10-06 15:52 UTC, ameen-11 commented on web/pages/urls.py
> +urlpatterns = [path("", home, name="home"),path("important_dates/",important_dates, name="important_dates"),path("tracks/",tracks, name="tracks")]
ran a formatter

2023-10-06 15:52 UTC, ameen-11 commented on web/templates/pages/tracks.html
beautified the page

2023-10-06 16:42 UTC, anirudhprabhakaran3 commented
Rebase from main once and resolve merge conflicts

2023-10-07 06:20 UTC, anirudhprabhakaran3 requested changes

2023-10-07 06:20 UTC, anirudhprabhakaran3 commented on web/templates/pages/home.html
> +<<<<<<< HEAD
This is not correct boss

2023-10-07 06:20 UTC, anirudhprabhakaran3 commented on web/templates/pages/home.html
> +>>>>>>> 7e911149c2d210a4e67347bad97c4742a236a457
Resolve merge conflicts properly!

2023-10-07 06:36 UTC, merged