8 add logos
anirudhprabhakaran3/pedes-website pull request #15
Opened 2023-10-06 20:26 UTC by MeerIsmailAli

added logos for the sponsor page please review

2023-10-07 09:16 UTC, anirudhprabhakaran3 commented
Rebase with main once, a few changes have been made there.

2023-10-07 13:11 UTC, anirudhprabhakaran3 requested changes

2023-10-07 13:11 UTC, anirudhprabhakaran3 commented on web/templates/pages/committee.html
> +    <div class="relative overflow-x-auto shadow-md sm:rounded-lg" style="border: 0.5px solid #c2c0c0;width: 90vw;">
Do not use custom styles! Please use whatever is provided by Flowbite. If you want to add something custom, use Tailwind, as Flowbite is made on top of tailwind.

2023-10-07 13:11 UTC, anirudhprabhakaran3 commented on web/templates/pages/committee.html
> +    <div class="relative overflow-x-auto shadow-md sm:rounded-lg" style="border: 0.5px solid #c2c0c0;width: 90vw;">
Remove styles here also, use appropriate classes.

2023-10-07 13:11 UTC, anirudhprabhakaran3 commented on web/templates/pages/committee.html
> +    <div class="relative overflow-x-auto shadow-md sm:rounded-lg" style="border: 0.5px solid #c2c0c0;width: 90vw;">
Styles

2023-10-07 13:11 UTC, anirudhprabhakaran3 commented on web/templates/pages/committee.html
> +    <div class="relative overflow-x-auto shadow-md sm:rounded-lg" style="border: 0.5px solid #c2c0c0;width: 90vw;">
Styles

2023-10-07 13:11 UTC, anirudhprabhakaran3 commented on web/templates/pages/committee.html
> +    <div class="relative overflow-x-auto shadow-md sm:rounded-lg" style="border: 0.5px solid #c2c0c0;width: 90vw;">
Styles

2023-10-07 13:11 UTC, anirudhprabhakaran3 commented on web/templates/pages/committee.html
> +    <div class="relative overflow-x-auto shadow-md sm:rounded-lg" style="border: 0.5px solid #c2c0c0;width: 90vw;">
Styles

2023-10-08 04:00 UTC, MeerIsmailAli commented
please review the changes in styles

2023-10-08 04:03 UTC, MeerIsmailAli commented
in the sponsors section, I coudnt find a proper nitk .svg embelem i tried to convert one but it didnt come out clearly

2023-10-11 08:03 UTC, anirudhprabhakaran3 commented
For NITK, you can use this.
![nitkwhite](https://github.com/anirudhprabhakaran3/pedes-website/assets/76864239/0618ef3d-958b-4346-bb95-d460f4b21252)

2023-10-11 08:04 UTC, anirudhprabhakaran3 commented
Btw, try experimenting with SVG and PNG. If PNG works well enough, and is good on responsive mobiles, you can use that too.

2023-10-12 10:24 UTC, anirudhprabhakaran3 approved these changes

2023-10-12 10:25 UTC, merged